import { useCallback, useEffect, useRef, useState } from 'react';
import {
  cancelGenerationJob,
  clearRecords,
  fetchActiveGenerationJob,
  fetchGenerationJob,
  fetchGenerationHistory,
  fetchLatestGenerationJob,
  fetchRecords,
  fetchSystemHealth,
  generateRecords,
  searchRecords,
} from './api';

const PAGE_SIZE = 100;
const MAX_LENGTH = 10;
const ALPHABET = 'abcdefghijklmnopqrstuvwxyz';

function maxSequenceNumber(maxLength) {
  let total = 0;
  for (let length = 1; length <= maxLength; length += 1) total += ALPHABET.length ** length;
  return total;
}

function formatDuration(seconds) {
  if (seconds === null || !Number.isFinite(seconds)) return '—';
  return seconds < 60 ? `${seconds.toFixed(1)} sec` : `${Math.floor(seconds / 60)}m ${Math.round(seconds % 60)}s`;
}

function StatusDot({ state }) {
  const className = state === 'online' || state === 'active' ? 'is-online' : state === 'unknown' ? 'is-unknown' : 'is-degraded';
  return <span className={`status-dot ${className}`} />;
}

function formatJobDate(date) {
  return new Date(date).toLocaleDateString(undefined, { month: 'short', day: 'numeric' });
}

function formatChartNumber(value) {
  return new Intl.NumberFormat(undefined, { notation: 'compact', maximumFractionDigits: 1 }).format(value || 0);
}

function JobLineChart({ jobs }) {
  const points = [...jobs].slice(0, 8).reverse();
  const max = Math.max(1, ...points.map((job) => job.generated || 0));
  const coords = points.map((job, index) => ({
    x: points.length < 2 ? 260 : 28 + (index * 464) / (points.length - 1),
    y: 145 - ((job.generated || 0) / max) * 112,
    job,
  }));
  const polyline = coords.map(({ x, y }) => `${x},${y}`).join(' ');

  return <div className="viz-chart line-chart">
    {points.length ? <>
      <svg viewBox="0 0 520 180" role="img" aria-label="Records generated by recent jobs">
        {[34, 71, 108, 145].map((y) => <line key={y} x1="28" x2="492" y1={y} y2={y} className="chart-grid-line" />)}
        <polyline points={polyline} className="line-chart-path" />
        {coords.map(({ x, y, job }) => <circle key={job._id} cx={x} cy={y} r="4" className="line-chart-point"><title>{`${job.generated.toLocaleString()} records · ${formatJobDate(job.createdAt)}`}</title></circle>)}
      </svg>
      <div className="viz-axis-labels"><span>{formatJobDate(points[0].createdAt)}</span><span>{formatJobDate(points[points.length - 1].createdAt)}</span></div>
    </> : <div className="viz-empty">Job activity will appear here after generation.</div>}
  </div>;
}

function JobBarChart({ jobs }) {
  const points = [...jobs].slice(0, 6).reverse();
  const max = Math.max(1, ...points.map((job) => job.generated || 0));
  return <div className="bar-chart" role="img" aria-label="Records generated in the six latest jobs">
    {points.length ? points.map((job, index) => <div className="bar-column" key={job._id}>
      <span className="bar-value" title={`${job.generated.toLocaleString()} records`}>{formatChartNumber(job.generated)}</span>
      <div className="bar-track"><div className={`bar-fill bar-fill-${index % 4}`} style={{ height: `${Math.max(4, (job.generated / max) * 100)}%` }} /></div>
      <small>{formatJobDate(job.createdAt)}</small>
    </div>) : <div className="viz-empty">No completed job data yet.</div>}
  </div>;
}

export default function App() {
  const ledgerRef = useRef(null);
  const lengthFilterRef = useRef('all');
  const [records, setRecords] = useState([]);
  const [totalRecords, setTotalRecords] = useState(0);
  const [matchingRecords, setMatchingRecords] = useState(0);
  const [firstValue, setFirstValue] = useState(null);
  const [firstSequence, setFirstSequence] = useState(null);
  const [lastValue, setLastValue] = useState(null);
  const [minLength, setMinLength] = useState(1);
  const [maxLength, setMaxLength] = useState(3);
  const [searchValue, setSearchValue] = useState('');
  const [searchResult, setSearchResult] = useState(null);
  const [generationJob, setGenerationJob] = useState(null);
  const [latestJob, setLatestJob] = useState(null);
  const [systemHealth, setSystemHealth] = useState(null);
  const [searchCount, setSearchCount] = useState(0);
  const [lastSearchMs, setLastSearchMs] = useState(null);
  const [lastDeletedCount, setLastDeletedCount] = useState(null);
  const [lengthFilter, setLengthFilter] = useState('all');
  const [jobStatusFilter, setJobStatusFilter] = useState('all');
  const [generationHistory, setGenerationHistory] = useState([]);
  const [loading, setLoading] = useState(false);
  const [pageLoading, setPageLoading] = useState(false);
  const [clearing, setClearing] = useState(false);
  const [error, setError] = useState(null);
  const [status, setStatus] = useState(null);
  const [activeView, setActiveView] = useState('dashboard');

  const loadPage = useCallback(async (after = 0, length = lengthFilterRef.current) => {
    setPageLoading(true);
    try {
      const data = await fetchRecords(after, PAGE_SIZE, length);
      setRecords(data.records);
      setTotalRecords(data.totalCount ?? data.count);
      setMatchingRecords(data.count);
      setFirstValue(data.firstValue);
      setFirstSequence(data.firstSequence);
      setLastValue(data.lastValue);
      if (data.firstValue) setMinLength(data.firstValue.length);
      return data;
    } catch (err) {
      setError(err.message);
      return null;
    } finally {
      setPageLoading(false);
    }
  }, []);

  const refreshHealth = useCallback(() => {
    fetchSystemHealth().then(setSystemHealth).catch(() => setSystemHealth(null));
  }, []);

  const loadHistory = useCallback(async (filter = 'all') => {
    try {
      const { jobs } = await fetchGenerationHistory(filter, 20);
      setGenerationHistory(jobs);
    } catch (err) {
      setError(err.message);
    }
  }, []);

  useEffect(() => {
    loadPage(0);
    fetchActiveGenerationJob().then(({ job }) => {
      setGenerationJob(job);
      if (job) {
        setMinLength(job.minLength || 1);
        setMaxLength(job.maxLength);
      }
    }).catch((err) => setError(err.message));
    fetchLatestGenerationJob().then(({ job }) => setLatestJob(job)).catch(() => {});
    refreshHealth();
  }, [loadPage, refreshHealth, loadHistory]);

  useEffect(() => {
    loadHistory(jobStatusFilter);
  }, [jobStatusFilter, loadHistory]);

  useEffect(() => {
    const timer = window.setInterval(refreshHealth, 5000);
    return () => window.clearInterval(timer);
  }, [refreshHealth]);

  useEffect(() => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }, [activeView]);

  const jobIsActive = generationJob && ['queued', 'running'].includes(generationJob.status);
  const jobId = generationJob?._id;
  const afterForSequencePage = useCallback((sequenceNumber) => firstSequence === null
    ? Math.floor((sequenceNumber - 1) / PAGE_SIZE) * PAGE_SIZE
    : firstSequence + Math.max(0, Math.floor((sequenceNumber - firstSequence) / PAGE_SIZE)) * PAGE_SIZE - 1,
  [firstSequence]);

  useEffect(() => {
    if (!jobId || !jobIsActive) return undefined;
    let timer;
    let stopped = false;
    async function pollJob() {
      try {
        const { job } = await fetchGenerationJob(jobId);
        if (stopped) return;
        setGenerationJob(job);
        setLatestJob(job);
        if (job.status === 'completed') {
          setStatus(`Inserted ${job.generated.toLocaleString()} records. Total: ${job.lastSequence.toLocaleString()}.`);
          await loadPage(afterForSequencePage(job.lastSequence));
          loadHistory(jobStatusFilter);
          refreshHealth();
        } else if (job.status === 'cancelled') {
          setStatus(`Generation stopped at record ${job.lastSequence.toLocaleString()}.`);
          await loadPage(afterForSequencePage(job.lastSequence));
          loadHistory(jobStatusFilter);
          refreshHealth();
        } else if (job.status === 'failed') {
          setError(`Generation stopped at record ${job.lastSequence.toLocaleString()}: ${job.error}`);
          loadHistory(jobStatusFilter);
          refreshHealth();
        } else {
          timer = window.setTimeout(pollJob, 1000);
        }
      } catch (err) {
        if (!stopped) {
          setError(err.message);
          timer = window.setTimeout(pollJob, 2000);
        }
      }
    }
    pollJob();
    return () => {
      stopped = true;
      window.clearTimeout(timer);
    };
  }, [jobId, jobIsActive, loadPage, afterForSequencePage, refreshHealth, loadHistory, jobStatusFilter]);

  async function handleGenerate(event) {
    event.preventDefault();
    setError(null);
    setStatus(null);
    const min = Number(minLength);
    const max = Number(maxLength);
    if (!Number.isInteger(min) || min < 1 || min > MAX_LENGTH) return setError(`Minimum length must be from 1 to ${MAX_LENGTH}.`);
    if (!Number.isInteger(max) || max < min || max > MAX_LENGTH) return setError(`Maximum length must be from ${min} to ${MAX_LENGTH}.`);
    if (firstValue && firstValue.length !== min) return setError('Clear the stored records before changing the minimum length.');
    setLoading(true);
    try {
      const { job } = await generateRecords(min, max);
      setGenerationJob(job);
      setLatestJob(job);
      setStatus('Generation job queued.');
      refreshHealth();
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }

  async function handleCancelGeneration() {
    if (!generationJob) return;
    try {
      const { job } = await cancelGenerationJob(generationJob._id);
      setGenerationJob(job);
      setStatus('Stopping after the current batch…');
    } catch (err) {
      setError(err.message);
    }
  }

  async function handleClear() {
    if (!window.confirm('Delete every stored record and generation job? This cannot be undone.')) return;
    setError(null);
    setStatus(null);
    setClearing(true);
    try {
      const result = await clearRecords();
      setRecords([]);
      setTotalRecords(0);
      setMatchingRecords(0);
      setFirstValue(null);
      setFirstSequence(null);
      setLastValue(null);
      lengthFilterRef.current = 'all';
      setLengthFilter('all');
      setMinLength(1);
      setSearchResult(null);
      setSearchValue('');
      setGenerationJob(null);
      setLatestJob(null);
      setGenerationHistory([]);
      setLastDeletedCount(result.deleted);
      ledgerRef.current?.scrollTo({ top: 0 });
      setStatus(`Cleared ${result.deleted.toLocaleString()} records. Sequence will restart at a.`);
      refreshHealth();
    } catch (err) {
      setError(err.message);
    } finally {
      setClearing(false);
    }
  }

  async function handleSearch(event) {
    event.preventDefault();
    setError(null);
    try {
      const result = await searchRecords(searchValue.trim());
      setSearchCount((count) => count + 1);
      setLastSearchMs(result.lookupTimeMs);
      setSearchResult(result);
      const found = result.record || result.queryRecord;
      if (found) {
        let pageStart = firstSequence;
        let activeLengthFilter = lengthFilter;
        if (lengthFilter !== 'all' && found.value.length !== Number(lengthFilter)) {
          activeLengthFilter = 'all';
          lengthFilterRef.current = 'all';
          setLengthFilter('all');
          const firstPage = await loadPage(0, 'all');
          pageStart = firstPage?.firstSequence ?? null;
        }
        const after = pageStart === null
          ? Math.floor((found.sequenceNumber - 1) / PAGE_SIZE) * PAGE_SIZE
          : pageStart + Math.max(0, Math.floor((found.sequenceNumber - pageStart) / PAGE_SIZE)) * PAGE_SIZE - 1;
        await loadPage(after, activeLengthFilter);
      } else if (result.related) {
        ledgerRef.current?.scrollTo({ top: 0, behavior: 'smooth' });
      }
    } catch (err) {
      setSearchResult(null);
      setError(err.message);
    }
  }

  const viewDetails = {
    dashboard: { title: 'Dashboard', subtitle: 'System health, generation speed and ledger totals.' },
    operations: { title: 'Controls', subtitle: 'Start, monitor and clear sequence generation jobs.' },
    search: { title: 'Search', subtitle: 'Find a generated value or sequence position.' },
    ledger: { title: 'Ledger', subtitle: 'Browse records and filter the sequence by letter length.' },
    system: { title: 'System', subtitle: 'Live service checks and detected application stack.' },
  }[activeView];

  async function goToPage(page) {
    if (firstSequence === null || page < 1) return;
    setSearchResult(null);
    await loadPage(firstSequence + (page - 1) * PAGE_SIZE - 1);
    ledgerRef.current?.scrollTo({ top: 0 });
  }

  async function openLedgerRecord(record) {
    let filter = lengthFilterRef.current;
    let pageStart = firstSequence;
    if (filter !== 'all' && record.value.length !== Number(filter)) {
      filter = 'all';
      lengthFilterRef.current = filter;
      setLengthFilter(filter);
      const firstPage = await loadPage(0, filter);
      pageStart = firstPage?.firstSequence ?? null;
    }
    const after = pageStart === null
      ? Math.floor((record.sequenceNumber - 1) / PAGE_SIZE) * PAGE_SIZE
      : pageStart + Math.max(0, Math.floor((record.sequenceNumber - pageStart) / PAGE_SIZE)) * PAGE_SIZE - 1;
    setActiveView('ledger');
    await loadPage(after, filter);
  }

  async function changeLengthFilter(value) {
    lengthFilterRef.current = value;
    setLengthFilter(value);
    setSearchResult(null);
    await loadPage(0, value);
  }

  const calculatedTarget = Number.isInteger(Number(minLength)) && Number.isInteger(Number(maxLength))
    && Number(minLength) >= 1 && Number(maxLength) >= Number(minLength) && Number(maxLength) <= MAX_LENGTH
    ? maxSequenceNumber(Number(maxLength)) - maxSequenceNumber(Number(minLength) - 1)
    : 0;
  const totalPages = Math.ceil(matchingRecords / PAGE_SIZE);
  const currentPage = records.length && firstSequence !== null
    ? Math.floor((records[0].sequenceNumber - firstSequence) / PAGE_SIZE) + 1
    : 1;
  const pageItems = [];
  if (totalPages <= 9) {
    for (let page = 1; page <= totalPages; page += 1) pageItems.push(page);
  } else {
    const visible = new Set([1, totalPages]);
    for (let page = Math.max(2, currentPage - 2); page <= Math.min(totalPages - 1, currentPage + 2); page += 1) visible.add(page);
    let previous = 0;
    for (const page of [...visible].sort((a, b) => a - b)) {
      if (page - previous > 1) pageItems.push(`gap-${page}`);
      pageItems.push(page);
      previous = page;
    }
  }

  const activeJob = jobIsActive ? generationJob : latestJob;
  const startedAt = activeJob?.createdAt ? new Date(activeJob.createdAt).getTime() : null;
  const endedAt = jobIsActive ? Date.now() : activeJob?.updatedAt ? new Date(activeJob.updatedAt).getTime() : null;
  const durationSeconds = startedAt && endedAt ? Math.max(0, (endedAt - startedAt) / 1000) : null;
  const rate = durationSeconds > 0 && activeJob?.generated ? activeJob.generated / durationSeconds : null;
  const runTarget = activeJob ? Math.max(1, activeJob.targetCount - activeJob.startSequence) : 1;
  const runProgress = activeJob ? Math.min(100, (activeJob.generated / runTarget) * 100) : 0;
  const apiState = systemHealth?.checks?.api || 'unknown';
  const databaseState = systemHealth?.checks?.database || 'unknown';
  const redisState = systemHealth?.checks?.redis || 'unknown';
  const workerState = systemHealth?.checks?.worker || 'unknown';
  const recentJobs = generationHistory.slice(0, 8);
  const jobStatusCounts = ['completed', 'running', 'queued', 'failed', 'cancelled'].map((name) => ({
    name,
    count: generationHistory.filter((job) => job.status === name).length,
  })).filter((item) => item.count > 0);
  const statusColors = { completed: '#718B78', running: '#C9B59C', queued: '#D9CFC7', failed: '#A44C3E', cancelled: '#9B9188' };
  const statusTotal = jobStatusCounts.reduce((sum, item) => sum + item.count, 0);
  let statusAngle = 0;
  const statusGradient = jobStatusCounts.map(({ name, count }) => {
    const start = statusAngle;
    statusAngle += (count / (statusTotal || 1)) * 360;
    return `${statusColors[name]} ${start}deg ${statusAngle}deg`;
  }).join(', ');

  return (
    <div className="app-shell">
      <aside className="sidebar">
        <button className="brand-mark" type="button" onClick={() => setActiveView('dashboard')} aria-label="Sequence Ledger home">SL</button>
        <div className="sidebar-brand"><strong>Sequence</strong><span>LEDGER / 01</span></div>
        <div className="sidebar-label">Workspace</div>
        <nav className="side-nav" aria-label="Workspace navigation">
          <button type="button" className={`side-link${activeView === 'dashboard' ? ' side-link-active' : ''}`} onClick={() => setActiveView('dashboard')}><span>01</span> Dashboard</button>
          <button type="button" className={`side-link${activeView === 'operations' ? ' side-link-active' : ''}`} onClick={() => setActiveView('operations')}><span>02</span> Controls</button>
          <button type="button" className={`side-link${activeView === 'search' ? ' side-link-active' : ''}`} onClick={() => setActiveView('search')}><span>03</span> Search</button>
          <button type="button" className={`side-link${activeView === 'ledger' ? ' side-link-active' : ''}`} onClick={() => setActiveView('ledger')}><span>04</span> Ledger</button>
          <button type="button" className={`side-link${activeView === 'system' ? ' side-link-active' : ''}`} onClick={() => setActiveView('system')}><span>05</span> System</button>
        </nav>
        <button className="sidebar-health" type="button" onClick={() => setActiveView('system')}><StatusDot state={systemHealth?.status === 'online' ? 'online' : 'degraded'} /><span><strong>{systemHealth?.status === 'online' ? 'All systems normal' : 'Check system status'}</strong><small>View service checks</small></span><span className="sidebar-chevron">↗</span></button>
        <div className="sidebar-foot">LOCAL WORKSPACE <span>v1.0</span></div>
      </aside>

      <div className="workspace">
        <header className="topbar"><div className="breadcrumb">WORKSPACE <span>/</span> {viewDetails.title.toUpperCase()}</div><button className="topbar-status" type="button" onClick={() => setActiveView('system')}><StatusDot state={systemHealth?.status === 'online' ? 'online' : 'degraded'} />{systemHealth?.status === 'online' ? 'All systems normal' : 'System checks'}<span className="topbar-time">{systemHealth?.checkedAt ? new Date(systemHealth.checkedAt).toLocaleTimeString() : 'Checking…'}</span></button></header>

        <main className="dashboard-main" id="overview">
          <section className="page-heading"><div><div className="eyebrow">SEQUENCE OPERATIONS / 0{['dashboard', 'operations', 'search', 'ledger', 'system'].indexOf(activeView) + 1}</div><h1>{viewDetails.title}</h1><p>{viewDetails.subtitle}</p></div>{activeView === 'dashboard' && <button type="button" className="quiet-button" onClick={() => { loadPage(0); refreshHealth(); }}>Refresh data <span>↻</span></button>}</section>

          {activeView === 'dashboard' && <section className="metric-grid" aria-label="Key statistics">
            <button className="metric-card metric-card-primary" type="button" onClick={() => setActiveView('ledger')}><span className="metric-label">RECORDS STORED <span>↗</span></span><strong>{totalRecords.toLocaleString()}</strong><small>{lastValue ? `Latest value ${lastValue}` : 'No records in ledger'}</small></button>
            <button className="metric-card" type="button" onClick={() => setActiveView('operations')}><span className="metric-label">GENERATION RATE <span>↗</span></span><strong>{rate ? Math.round(rate).toLocaleString() : '—'}<em>{rate ? ' rec/s' : ''}</em></strong><small>{activeJob ? `${activeJob.generated.toLocaleString()} records in latest job` : 'Run a job to measure speed'}</small></button>
            <button className="metric-card" type="button" onClick={() => setActiveView('operations')}><span className="metric-label">LATEST RUN TIME <span>↗</span></span><strong>{durationSeconds !== null ? formatDuration(durationSeconds) : '—'}</strong><small>{activeJob ? `Last operation: ${activeJob.status}` : 'No generation history yet'}</small></button>
            <button className="metric-card" type="button" onClick={() => setActiveView('search')}><span className="metric-label">SEARCH LOOKUPS <span>↗</span></span><strong>{searchCount.toLocaleString()}</strong><small>{lastSearchMs !== null ? `Latest lookup ${lastSearchMs.toFixed(2)} ms` : 'No searches this session'}</small></button>
            <button className="metric-card" type="button" onClick={() => setActiveView('operations')}><span className="metric-label">LAST DELETE <span>↗</span></span><strong>{lastDeletedCount === null ? '—' : lastDeletedCount.toLocaleString()}</strong><small>{lastDeletedCount === null ? 'No deletes this session' : 'Records cleared this session'}</small></button>
          </section>}

          {activeView === 'dashboard' && <section className="analytics-grid" aria-label="Dashboard analytics">
            <section className="panel viz-panel viz-line-panel"><div className="panel-heading"><div><div className="eyebrow">01 / TREND</div><h2>Generation over time</h2></div><span className="panel-note">RECORDS / JOB</span></div><JobLineChart jobs={recentJobs} /></section>
            <section className="panel viz-panel"><div className="panel-heading"><div><div className="eyebrow">02 / VOLUME</div><h2>Recent job volume</h2></div><span className="panel-note">LATEST 6</span></div><JobBarChart jobs={generationHistory} /></section>
            <section className="panel viz-panel viz-donut-panel"><div className="panel-heading"><div><div className="eyebrow">03 / STATUS</div><h2>Job outcomes</h2></div><span className="panel-note">LATEST 20</span></div><div className="donut-layout">{statusTotal ? <div className="donut-chart" style={{ background: `conic-gradient(${statusGradient})` }} role="img" aria-label={`${statusTotal} recent jobs by status`}><div className="donut-hole"><strong>{statusTotal}</strong><small>jobs</small></div></div> : <div className="donut-chart donut-chart-empty"><div className="donut-hole"><strong>0</strong><small>jobs</small></div></div>}<ul className="donut-legend">{jobStatusCounts.length ? jobStatusCounts.map(({ name, count }) => <li key={name}><i style={{ background: statusColors[name] }} /><span>{name}</span><strong>{count}</strong></li>) : <li className="donut-no-data">No job outcomes yet</li>}</ul></div></section>
            <section className="panel viz-panel data-table-panel"><div className="panel-heading"><div><div className="eyebrow">04 / RECENT DATA</div><h2>Latest generation jobs</h2></div><button className="text-button" type="button" onClick={() => setActiveView('operations')}>View all →</button></div><div className="dashboard-table-wrap"><table className="dashboard-table"><thead><tr><th>Status</th><th>Generated</th><th>Length range</th><th>Started</th></tr></thead><tbody>{generationHistory.slice(0, 8).map((job) => <tr key={job._id} onClick={() => { setLatestJob(job); if (['queued', 'running'].includes(job.status)) setGenerationJob(job); setActiveView('operations'); }}><td><span className={`table-status table-status-${job.status}`}><i />{job.status}</span></td><td>{job.generated.toLocaleString()}</td><td>{job.minLength}–{job.maxLength} letters</td><td>{formatJobDate(job.createdAt)}</td></tr>)}{generationHistory.length === 0 && <tr><td className="table-empty" colSpan="4">No generation jobs yet. Start one from Controls to see analytics.</td></tr>}</tbody></table></div></section>
          </section>}

          {error && <div className="banner banner-error" role="alert">{error}</div>}
          {status && !error && <div className="banner banner-ok" role="status">{status}</div>}

          <section className={`dashboard-grid view-${activeView}`} hidden={activeView === 'ledger'}>
            <section className="panel operations-panel" id="operations" hidden={activeView !== 'operations'}>
              <div className="panel-heading"><div><div className="eyebrow">01 / CREATE</div><h2>Generation controls</h2></div><span className="panel-note">Batch size 25,000</span></div>
              <form onSubmit={handleGenerate} className="generate-form">
                <label htmlFor="min-length">Min letters</label><input id="min-length" type="number" min="1" max={MAX_LENGTH} value={minLength} onChange={(event) => { const value = event.target.value; setMinLength(value); if (Number(value) > Number(maxLength)) setMaxLength(value); }} disabled={loading || Boolean(jobIsActive) || clearing || Boolean(firstValue)} />
                <label htmlFor="max-length">Max letters</label><input id="max-length" type="number" min="1" max={MAX_LENGTH} value={maxLength} onChange={(event) => { const value = event.target.value; if (Number(value) < Number(minLength)) { if (firstValue) setMaxLength(String(minLength)); else { setMaxLength(value); setMinLength(value); } } else setMaxLength(value); }} disabled={loading || Boolean(jobIsActive) || clearing} />
                <div className="target-count"><span>ESTIMATED RANGE</span><strong>{calculatedTarget.toLocaleString()}</strong><small>records</small></div>
                <button className="primary-button" type="submit" disabled={loading || Boolean(jobIsActive) || clearing}>{loading ? 'Starting…' : jobIsActive ? 'In progress' : 'Generate records'} <span>→</span></button>
              </form>
              {Boolean(firstValue) && <div className="inline-note">Minimum length is locked while records exist. Clear the ledger before starting another range.</div>}
              {jobIsActive && <div className="job-progress" aria-live="polite"><div className="progress-heading"><span>{generationJob.generated.toLocaleString()} / {(generationJob.targetCount - generationJob.startSequence).toLocaleString()} inserted</span><button type="button" onClick={handleCancelGeneration} disabled={generationJob.cancelRequested}>{generationJob.cancelRequested ? 'Stopping…' : 'Stop job'}</button></div><progress max="100" value={runProgress} aria-label="Generation progress" /><small>Database position {generationJob.lastSequence.toLocaleString()} / {generationJob.targetCount.toLocaleString()}</small></div>}
              <div className="operation-footer"><span>LAST VALUE <strong>{lastValue || '—'}</strong></span><span>LAST DELETION <strong>{lastDeletedCount === null ? '—' : `${lastDeletedCount.toLocaleString()} records`}</strong></span><button className="clear-button" type="button" onClick={handleClear} disabled={Boolean(jobIsActive) || clearing || totalRecords === 0}>{clearing ? 'Clearing…' : 'Clear ledger'}</button></div>
            </section>

            <section className="panel activity-panel" hidden={activeView !== 'operations'}><div className="panel-heading"><div><div className="eyebrow">02 / ACTIVITY</div><h2>Generation history</h2></div><label className="filter-control"><span>STATUS</span><select aria-label="Filter generation jobs by status" value={jobStatusFilter} onChange={(event) => setJobStatusFilter(event.target.value)}><option value="all">All jobs</option><option value="queued">Queued</option><option value="running">Running</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option><option value="failed">Failed</option></select></label></div>{activeJob ? <><div className="activity-summary"><strong>{activeJob.generated.toLocaleString()}</strong><span>records inserted</span><span className="activity-rate">{rate ? `${Math.round(rate).toLocaleString()} / sec` : 'Rate unavailable'}</span></div><div className="activity-chart" role="img" aria-label={`Latest job is ${runProgress.toFixed(0)} percent complete`}><div className="chart-axis"><span>0</span><span>{runTarget.toLocaleString()} target</span></div><div className="chart-track"><div className="chart-fill" style={{ width: `${runProgress}%` }} /></div><div className="chart-foot"><span>{runProgress.toFixed(1)}% complete</span><span>{formatDuration(durationSeconds)}</span></div></div></> : <div className="chart-empty"><span className="chart-empty-mark">—</span><p>Generation activity will appear here after the first job.</p></div>}<div className="activity-meta"><span>QUEUE <strong>{systemHealth?.queueName || 'sequence-generation'}</strong></span><span>WAITING <strong>{systemHealth?.queue?.waiting ?? '—'}</strong></span><span>FAILED <strong>{systemHealth?.queue?.failed ?? '—'}</strong></span></div><div className="history-list">{generationHistory.length ? generationHistory.slice(0, 6).map((job) => <button type="button" key={job._id} className={`history-row${activeJob?._id === job._id ? ' history-row-active' : ''}`} onClick={() => { setLatestJob(job); if (['queued', 'running'].includes(job.status)) setGenerationJob(job); else if (!jobIsActive) setGenerationJob(null); }}><span className={`history-status history-status-${job.status}`}>{job.status}</span><span className="history-range">{job.minLength}–{job.maxLength} letters</span><strong>{job.generated.toLocaleString()}</strong><small>{new Date(job.createdAt).toLocaleDateString()}</small></button>) : <p className="history-empty">No jobs match this status.</p>}</div></section>

            <section className="panel search-panel" id="search-panel" hidden={activeView !== 'search'}><div className="panel-heading"><div><div className="eyebrow">03 / FIND</div><h2>Search ledger</h2></div><span className="panel-note">Value or sequence</span></div><form className="search-form" onSubmit={handleSearch}><label className="visually-hidden" htmlFor="search-value">Find a value or position</label><input id="search-value" type="search" value={searchValue} onChange={(event) => setSearchValue(event.target.value)} placeholder="e.g. ggg or 123" autoComplete="off" /><button type="submit">Search <span>↗</span></button></form><p className="search-hint">Search exact values, sequence positions, or inspect nearby values.</p>{searchResult && <div className={`search-result ${searchResult.record || searchResult.queryRecord ? 'search-result-found' : ''}`} role="status"><strong>{searchResult.record?.value || searchResult.queryRecord?.value || searchResult.query || 'Search'}</strong><span>{searchResult.record ? `Found at #${searchResult.record.sequenceNumber.toLocaleString()}` : searchResult.queryRecord ? `Found at #${searchResult.queryRecord.sequenceNumber.toLocaleString()}` : searchResult.related ? 'Related values are listed in the ledger' : 'No matching record'}</span><small>{searchResult.lookupTimeMs.toFixed(2)} ms</small>{(searchResult.record || searchResult.queryRecord) && <button type="button" onClick={() => openLedgerRecord(searchResult.record || searchResult.queryRecord)}>Open record →</button>}</div>}</section>

            <section className="panel system-panel" id="system-panel" hidden={activeView !== 'dashboard' && activeView !== 'system'}><div className="panel-heading"><div><div className="eyebrow">04 / SERVICES</div><h2>System status</h2></div><button className="quiet-button" type="button" onClick={refreshHealth}>Check now ↻</button></div><div className="service-list">
              <button type="button" className="service-row" onClick={refreshHealth}><StatusDot state={apiState} /><span><strong>API</strong><small>Node.js · Express 4</small></span><b>{apiState}</b></button>
              <button type="button" className="service-row" onClick={refreshHealth}><StatusDot state={databaseState} /><span><strong>Database</strong><small>MongoDB · Mongoose 8</small></span><b>{databaseState}</b></button>
              <button type="button" className="service-row" onClick={refreshHealth}><StatusDot state={redisState} /><span><strong>Queue service</strong><small>Redis-compatible · BullMQ 5</small></span><b>{redisState}</b></button>
              <button type="button" className="service-row" onClick={refreshHealth}><StatusDot state={workerState} /><span><strong>Generation worker</strong><small>{jobIsActive ? 'Processing a job' : 'Background processor'}</small></span><b>{workerState}</b></button>
              <div className="service-row service-row-static"><span className="service-mark">UI</span><span><strong>Frontend</strong><small>React 18 · Vite 5</small></span><b>active</b></div>
              <div className="service-row service-row-static"><span className="service-mark">—</span><span><strong>Response cache</strong><small>Redis is used for BullMQ queueing</small></span><b>not configured</b></div>
            </div><div className="system-footnote">Status refreshes every 5 seconds. Queue storage and response caching are separate services.</div></section>
          </section>

          {activeView === 'search' && searchResult?.related && <section className="related-results" aria-label="Related search values">{searchResult.queryRecord && <div className="exact-query-result"><strong>{searchResult.queryRecord.value}</strong><span>Exact match, index #{searchResult.queryRecord.sequenceNumber}</span></div>}<table><caption>Related values for “{searchResult.query}”</caption><thead><tr><th scope="col">Value</th><th scope="col">Index</th><th scope="col">Status</th></tr></thead><tbody>{searchResult.related.map((item) => <tr key={item.value}><td className="related-value">{item.value}</td><td>{item.record ? <button className="related-index-button" type="button" onClick={() => openLedgerRecord(item.record)}>{item.sequenceNumber}</button> : item.sequenceNumber}</td><td className={item.record ? 'related-status-generated' : 'related-status-pending'}>{item.record ? 'Generated' : 'Pending'}</td></tr>)}</tbody></table></section>}

          <section className="panel ledger-panel" id="ledger-panel" hidden={activeView !== 'ledger'}><div className="panel-heading ledger-heading"><div><div className="eyebrow">05 / RECORDS</div><h2>Sequence ledger</h2><p>{matchingRecords.toLocaleString()} matching records · page {totalPages ? currentPage.toLocaleString() : 0} of {totalPages.toLocaleString()}</p></div><div className="ledger-tools"><label className="filter-control"><span>LENGTH</span><select aria-label="Filter ledger by letter length" value={lengthFilter} onChange={(event) => changeLengthFilter(event.target.value)}><option value="all">All lengths</option>{Array.from({ length: MAX_LENGTH }, (_, index) => <option key={index + 1} value={index + 1}>{index + 1} letter{index === 0 ? '' : 's'}</option>)}</select></label><div className="ledger-actions"><button className="quiet-button" type="button" onClick={() => ledgerRef.current?.scrollTo({ top: 0, behavior: 'smooth' })}>Top ↑</button><button className="quiet-button" type="button" onClick={() => ledgerRef.current?.scrollTo({ top: ledgerRef.current.scrollHeight, behavior: 'smooth' })}>Bottom ↓</button></div></div></div><nav className="ledger-navigation" aria-label="Ledger pages"><button type="button" disabled={currentPage <= 1 || pageLoading} onClick={() => goToPage(currentPage - 1)}>← Prev</button>{pageItems.map((item) => typeof item === 'number' ? <button key={item} type="button" className={item === currentPage ? 'page-number page-number-current' : `page-number${item === totalPages ? ' page-number-last' : ''}`} aria-current={item === currentPage ? 'page' : undefined} disabled={pageLoading} onClick={() => item !== currentPage && goToPage(item)}>{item}</button> : <span key={item} className="page-gap" aria-hidden="true">…</span>)}<button type="button" disabled={pageLoading || currentPage >= totalPages} onClick={() => goToPage(currentPage + 1)}>Next →</button></nav><div className="ledger" ref={ledgerRef}>{pageLoading ? <p className="empty">Loading records…</p> : records.length === 0 ? <p className="empty">No records match this filter.</p> : <div className="ledger-grid">{records.map((record) => <div key={record.sequenceNumber} data-sequence={record.sequenceNumber} className={`ledger-cell${searchResult?.record?.sequenceNumber === record.sequenceNumber || searchResult?.queryRecord?.sequenceNumber === record.sequenceNumber ? ' ledger-cell-found' : ''}`}><span className="ledger-index">{record.sequenceNumber.toLocaleString()}</span><span className="ledger-value">{record.value}</span></div>)}</div>}</div></section>
          <footer className="page-footer"><span>SEQUENCE LEDGER / INTERNAL TOOL</span><span>FRONTEND REACT · VITE / API EXPRESS</span></footer>
        </main>
      </div>
    </div>
  );
}
